name: Deploy Frontend

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: cloud
    steps:
      - uses: actions/checkout@v4

      - name: Run Foxogram Frontend
        run: docker compose up foxogram-frontend-dev -d --build
